<?php
/**
 * @author Ondřej Doněk <ondrejd@gmail.com>
 * @link https://github.com/ondrejd/odwp-acadp-lower_price for the canonical source repository
 * @license https://www.gnu.org/licenses/gpl-3.0.en.html GNU General Public License 3.0
 * @package odwp-acadp-lower_price
 * @see ALP_Plugin::admin_menu()
 * @since 1.0.0
 */

if( ! defined( 'ABSPATH' ) ) {
    exit;
}

if( ! class_exists( 'ALP_Acadp_Items_Table' ) ) {
    require_once( DL_PATH . 'src/ALP_Acadp_Items_Table.php' );
}

/**
 * @var ALP_Acadp_Items_Table $alp_acadp_items_table
 */
$alp_acadp_items_table = new ALP_Acadp_Items_Table();
$alp_acadp_items_table->prepare_items();

/**
 * @var array $next
 */
$next = ALP_Plugin::get_next_scheduled();

// Print message about next scheduled running of lower price script.
$msg1 = __( 'Příští naplánované snížení cen proběhne dnes v <b>%s</b> (za <b>%s hodin</b>).', ALP_SLUG );
$hours = ( $next['hours_left'] == 1 ) ? '1 hodinu' : ( ( $next['hours_left'] > 4 ) ? $next['hours_left'] . ' hodin' : $next['hours_left'] . ' hodiny' );

if( $next['is_next_tomorrow'] ) {
    $msg1 = __( 'Příští naplánované snížení cen proběhne zítra v <b>%s</b> (za <b>%s hodin</b>).', ALP_SLUG );
}

ALP_Plugin::print_admin_notice( sprintf( $msg1, $next['next_scheduled'], $next['hours_left'] ), 'info', true );

// Print message about last executed lower price script.
$last_scheduled = ALP_Plugin::get_option( 'last_execution_time' );
if( ! empty( $last_scheduled ) && $last_scheduled != '00:00' ) {// Byl uz skript vubec spusten?
    $msg2 = __( 'Skript pro snížení cen byl naposledy spuštěn: <b>%s</b>', ALP_SLUG );
    ALP_Plugin::print_admin_notice( sprintf( $msg2, $last_scheduled ), 'info', true );
} else {
    $msg2 = __( 'Skript pro snížení cen ještě nebyl nikdy spuštěn!', ALP_SLUG );
    ALP_Plugin::print_admin_notice( $msg2, 'error', true );
}

?>
<div class="wrap">
    <h1><?php _e( 'Přehled cen inzerátů', ALP_SLUG ) ?></h1>
    <form method="post">
        <input type="hidden" name="page" value="<?php echo ALP_Acadp_Items_List_Screen::SLUG ?>">
        <?php $alp_acadp_items_table->display() ?>
    </form>
</div>












