<?php
/**
 * @author Ondřej Doněk <ondrejd@gmail.com>
 * @link https://github.com/ondrejd/odwp-acadp-lower_price for the canonical source repository
 * @license https://www.gnu.org/licenses/gpl-3.0.en.html GNU General Public License 3.0
 * @package odwp-acadp-lower_price
 * @see ALP_Plugin::admin_menu()
 * @since 1.0.0
 */

if( ! defined( 'ABSPATH' ) ) {
    exit;
}

?>
<div class="wrap">
    <h1><?php _e( 'Nastavení pro plugin Pravidelné snižování cen', ALP_SLUG ) ?></h1>
    <form action="options.php" method="post"><?php
        settings_fields( ALP_SLUG );
        do_settings_sections( ALP_SLUG );
        submit_button();
    ?></form>
</div>
