<?php
/**
 * @author Ondřej Doněk <ondrejd@gmail.com>
 * @link https://github.com/ondrejd/odwp-acadp-lower_price for the canonical source repository
 * @license https://www.gnu.org/licenses/gpl-3.0.en.html GNU General Public License 3.0
 * @package odwp-acadp-lower_price
 * @see ALP_Plugin::render_settings_section_1()
 * @since 1.0.0
 */

if( ! defined( 'ABSPATH' ) ) {
    exit;
}

?>
<p class="description">
    <?php printf( __( 'Nastavte čas pro spouštění skriptu pro pravidelné snižování cen. V nastavený čas bude každý den skript spuštěn pomocí <a href="%s" target="blank">wp_cron</a>.', ALP_SLUG ), 'https://developer.wordpress.org/reference/functions/wp_cron/' ) ?>
</p>
